from fastapi import APIRouter, HTTPException, status, Depends, Query
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
import logging
from typing import List, Any

from app import schemas, crud
from app.api import deps

logger = logging.getLogger(__name__)
router = APIRouter()

@router.post("/", response_model=schemas.Agent, status_code=status.HTTP_201_CREATED)
def register_agent(agent_in: schemas.AgentCreate, db: Session = Depends(deps.get_db)):
    """Register a new agent in the system.

    The agent_id is generated by the service.
    The public_key must be unique.
    """
    try:
        # The public_key in agent_in is validated to bytes by Pydantic schema
        agent = crud.agent.create(db=db, obj_in=agent_in)
    except IntegrityError as e:
        # This typically means unique constraint failed (e.g., public_key already exists)
        db.rollback()
        logger.warning(f"Integrity error during agent registration (e.g. duplicate public key): {agent_in.public_key[:20]}... - Error: {e}")
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT, # 409 Conflict for duplicate resource
            detail="Agent with this public key already exists.",
        )
    except ValueError as e:
        # Catch ValueErrors from CRUD layer (e.g., if public_key bytes somehow invalid there, though schema should catch first)
        db.rollback()
        logger.error(f"Value error during agent creation: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        db.rollback()
        logger.error(f"Unexpected error creating agent: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not create agent due to an internal error."
        )
    return agent # Pydantic will serialize this using schemas.Agent (ORM mode)

@router.get("/{agent_id}", response_model=schemas.Agent)
def read_agent(agent_id: str, db: Session = Depends(deps.get_db)):
    """Get agent details by agent_id."""
    db_agent = crud.agent.get_by_agent_id(db=db, agent_id=agent_id)
    if db_agent is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    return db_agent # Pydantic will serialize this using schemas.Agent

@router.get("/", response_model=schemas.AgentList)
def list_agents(
    db: Session = Depends(deps.get_db),
    skip: int = Query(0, ge=0, description="Number of records to skip for pagination"),
    limit: int = Query(100, ge=1, le=500, description="Maximum number of records to return")
):
    """Retrieve a list of agents with pagination."""
    try:
        agents = crud.agent.get_multi(db, skip=skip, limit=limit)
        # For total count, CRUDBase might need a count method, or we do it here
        # total_count = db.query(crud.agent.model).count() # Simple count, can be slow on huge tables
        # A more optimized count might be needed for production
        # For now, let's assume crud.agent can provide it or we do a basic one.
        # Placeholder for count - in a real app, get this efficiently.
        # total_count = len(agents) if limit is effectively unbounded or no skip, otherwise it's complex.
        # Let's assume get_multi could be extended or we add a count method to CRUDBase/CRUDAgent
        # For this iteration, we will omit total count if not easily available or just count what's returned for simplicity.
        # A better approach for total would be: total = crud.agent.get_count(db)
        
        # If crud.agent does not have get_count, we can simulate it for now or make total optional in AgentList
        # For the purpose of this exercise, let's make total count based on the returned list if not fully implemented
        # This is NOT a proper pagination total for all records.
        # Ideally, AgentList schema might make total optional or crud layer would provide it.

        # Let's refine `schemas.AgentList` to make total optional, or implement crud.agent.count()
        # For now, let's use a dummy total for placeholder if needed by AgentList schema
        # Assuming AgentList requires total:
        # total_count = len(crud.agent.get_multi(db, limit=None)) # Inefficient for real app

        # For now, let's assume total is not strictly required or we pass just the count of items in the current page.
        # This means `AgentList` schema would need `total` to be Optional or a different approach taken.
        # Let's assume for now we just return the current list and `AgentList` will be adapted if needed.

    except Exception as e:
        logger.error(f"Error listing agents: {e}", exc_info=True)
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Failed to retrieve agent list.")
    
    # If AgentList strictly needs total, this part needs a proper count from CRUD
    # This is a simplified response for now. A real app needs a proper total count for pagination.
    return schemas.AgentList(agents=agents, total=len(agents)) # Using len(agents) as a placeholder total

@router.patch("/{agent_id}", response_model=schemas.Agent)
def update_agent(
    agent_id: str,
    agent_in: schemas.AgentUpdate,
    db: Session = Depends(deps.get_db)
):
    """Update an agent's details (name, description, status)."""
    db_agent = crud.agent.get_by_agent_id(db=db, agent_id=agent_id)
    if not db_agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    try:
        updated_agent = crud.agent.update(db=db, db_obj=db_agent, obj_in=agent_in)
    except Exception as e: # Catch potential errors from CRUDBase update
        logger.error(f"Error updating agent {agent_id}: {e}", exc_info=True)
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Could not update agent.")
    return updated_agent

@router.delete("/{agent_id}", response_model=schemas.Agent)
def delete_agent(agent_id: str, db: Session = Depends(deps.get_db)):
    """Deactivate an agent by setting its status to 'inactive' (soft delete)."""
    
    # The crud.agent.remove() method now performs a deactivation (soft delete)
    # and returns the updated agent object or None if not found.
    deactivated_agent = crud.agent.remove(db=db, id=agent_id) 
    
    if not deactivated_agent:
        logger.warning(f"Attempt to delete/deactivate non-existent agent: {agent_id}")
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    
    logger.info(f"Agent {agent_id} successfully deactivated (soft deleted). Status: {deactivated_agent.status}")
    # Return the agent object, which will now have status="inactive"
    return deactivated_agent 