from fastapi import APIRouter, HTTPException, status, Depends, Query
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
import logging
from typing import List, Any

from app import schemas, crud
from app.api import deps

logger = logging.getLogger(__name__)
router = APIRouter()

@router.post("/", response_model=schemas.Agent, status_code=status.HTTP_201_CREATED)
def register_agent(agent_in: schemas.AgentCreate, db: Session = Depends(deps.get_db)):
    """Register a new agent in the system.

    The agent_id is generated by the service.
    The public_key must be unique.
    """
    try:
        # The public_key in agent_in is validated to bytes by Pydantic schema
        agent = crud.agent.create(db=db, obj_in=agent_in)
    except IntegrityError as e:
        # This typically means unique constraint failed (e.g., public_key already exists)
        db.rollback()
        logger.warning(f"Integrity error during agent registration (e.g. duplicate public key): {agent_in.public_key[:20]}... - Error: {e}")
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT, # 409 Conflict for duplicate resource
            detail="Agent with this public key already exists.",
        )
    except ValueError as e:
        # Catch ValueErrors from CRUD layer (e.g., if public_key bytes somehow invalid there, though schema should catch first)
        db.rollback()
        logger.error(f"Value error during agent creation: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        db.rollback()
        logger.error(f"Unexpected error creating agent: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not create agent due to an internal error."
        )
    return agent # Pydantic will serialize this using schemas.Agent (ORM mode)

@router.get("/{agent_id}", response_model=schemas.Agent)
def read_agent(agent_id: str, db: Session = Depends(deps.get_db)):
    """Get agent details by agent_id."""
    db_agent = crud.agent.get_by_agent_id(db=db, agent_id=agent_id)
    if db_agent is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    return db_agent # Pydantic will serialize this using schemas.Agent

@router.get("/", response_model=schemas.AgentList)
def list_agents(
    db: Session = Depends(deps.get_db),
    skip: int = Query(0, ge=0, description="Number of records to skip for pagination"),
    limit: int = Query(100, ge=1, le=500, description="Maximum number of records to return")
):
    """Retrieve a list of agents with pagination."""
    try:
        agents = crud.agent.get_multi(db, skip=skip, limit=limit)
        # logger.info(f"[ENDPOINT_DEBUG] crud.agent.get_multi returned: {len(agents)} agents. First one if any: {agents[0].__dict__ if agents else 'None'}")
        
        agent_list_response = schemas.AgentList(agents=agents, total=len(agents))
        # logger.info(f"[ENDPOINT_DEBUG] AgentList Pydantic model created. Number of agents in model: {len(agent_list_response.agents)}")
        return agent_list_response
    except Exception as e:
        logger.error(f"Error listing agents in endpoint: {e}", exc_info=True)
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Failed to retrieve agent list.")

@router.patch("/{agent_id}", response_model=schemas.Agent)
def update_agent(
    agent_id: str,
    agent_in: schemas.AgentUpdate,
    db: Session = Depends(deps.get_db)
):
    """Update an agent's details (name, description, status)."""
    db_agent = crud.agent.get_by_agent_id(db=db, agent_id=agent_id)
    if not db_agent:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    try:
        updated_agent = crud.agent.update(db=db, db_obj=db_agent, obj_in=agent_in)
    except Exception as e: # Catch potential errors from CRUDBase update
        logger.error(f"Error updating agent {agent_id}: {e}", exc_info=True)
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Could not update agent.")
    return updated_agent

@router.delete("/{agent_id}", response_model=schemas.Agent)
def delete_agent(agent_id: str, db: Session = Depends(deps.get_db)):
    """Deactivate an agent by setting its status to 'inactive' (soft delete)."""
    
    # The crud.agent.remove() method now performs a deactivation (soft delete)
    # and returns the updated agent object or None if not found.
    deactivated_agent = crud.agent.remove(db=db, id=agent_id) 
    
    if not deactivated_agent:
        logger.warning(f"Attempt to delete/deactivate non-existent agent: {agent_id}")
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Agent not found")
    
    logger.info(f"Agent {agent_id} successfully deactivated (soft deleted). Status: {deactivated_agent.status}")
    # Return the agent object, which will now have status="inactive"
    return deactivated_agent 