"""add_secrets_table"""

# revision identifiers, used by Alembic.
revision = '203db040fcb3'
down_revision = 'a24369bdaffd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_id'), 'secrets', ['id'], unique=False)
    op.create_index(op.f('ix_secrets_name'), 'secrets', ['name'], unique=True)
    op.alter_column('agents', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment='Unique identifier for the agent (e.g., agent-<uuid>)',
               existing_nullable=False)
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Optional human-readable name for the agent.',
               existing_nullable=True)
    op.alter_column('agents', 'description',
               existing_type=sa.TEXT(),
               comment='Optional description for the agent.',
               existing_nullable=True)
    op.alter_column('agents', 'current_public_key',
               existing_type=postgresql.BYTEA(),
               comment='The current long-term Ed25519 public key for the agent (raw bytes).',
               existing_nullable=False)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status of the agent (e.g., active, inactive, revoked).',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the agent record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the agent record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the agent was last seen (e.g., issued a credential).',
               existing_nullable=True)
    op.alter_column('credentials', 'credential_id',
               existing_type=sa.VARCHAR(),
               comment='Unique identifier for this credential instance (e.g., cred-<uuid>)',
               existing_nullable=False)
    op.alter_column('credentials', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment='Identifier of the agent this credential belongs to.',
               existing_nullable=False)
    op.alter_column('credentials', 'ephemeral_public_key',
               existing_type=postgresql.BYTEA(),
               comment='The ephemeral X25519 public key associated with this credential (bytes).',
               existing_nullable=False)
    op.alter_column('credentials', 'signature',
               existing_type=postgresql.BYTEA(),
               comment="Signature of the ephemeral_public_key using the agent's long-term key (bytes).",
               existing_nullable=True)
    op.alter_column('credentials', 'scope',
               existing_type=sa.VARCHAR(),
               comment='Scope of access granted by this credential.',
               existing_nullable=True)
    op.alter_column('credentials', 'origin_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Optional JSON containing origin context details (hostname, IP, etc.).',
               existing_nullable=True)
    op.alter_column('credentials', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the credential was issued.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the credential expires.',
               existing_nullable=False)
    op.alter_column('credentials', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the credential was revoked (NULL if not revoked).',
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the credential was revoked (NULL if not revoked).',
               existing_nullable=True)
    op.alter_column('credentials', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the credential expires.',
               existing_nullable=False)
    op.alter_column('credentials', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the credential was issued.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'origin_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Optional JSON containing origin context details (hostname, IP, etc.).',
               existing_nullable=True)
    op.alter_column('credentials', 'scope',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Scope of access granted by this credential.',
               existing_nullable=True)
    op.alter_column('credentials', 'signature',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment="Signature of the ephemeral_public_key using the agent's long-term key (bytes).",
               existing_nullable=True)
    op.alter_column('credentials', 'ephemeral_public_key',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='The ephemeral X25519 public key associated with this credential (bytes).',
               existing_nullable=False)
    op.alter_column('credentials', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Identifier of the agent this credential belongs to.',
               existing_nullable=False)
    op.alter_column('credentials', 'credential_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Unique identifier for this credential instance (e.g., cred-<uuid>)',
               existing_nullable=False)
    op.alter_column('agents', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the agent was last seen (e.g., issued a credential).',
               existing_nullable=True)
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the agent record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the agent record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Status of the agent (e.g., active, inactive, revoked).',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('agents', 'current_public_key',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='The current long-term Ed25519 public key for the agent (raw bytes).',
               existing_nullable=False)
    op.alter_column('agents', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional description for the agent.',
               existing_nullable=True)
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Optional human-readable name for the agent.',
               existing_nullable=True)
    op.alter_column('agents', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Unique identifier for the agent (e.g., agent-<uuid>)',
               existing_nullable=False)
    op.drop_index(op.f('ix_secrets_name'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_id'), table_name='secrets')
    op.drop_table('secrets')
    # ### end Alembic commands ###