"""Add credential table and update agent"""

# revision identifiers, used by Alembic.
revision = '288224a3929d'
down_revision = '8a916b49e686'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Unique identifier for the agent (e.g., agent-<uuid>)',
               existing_nullable=False)
    op.alter_column('agents', 'current_public_key',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='The current long-term Ed25519 public key for the agent (bytes).',
               existing_nullable=False)
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the agent record was created.',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'credential_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Unique identifier for this credential instance (e.g., cred-<uuid>)',
               existing_nullable=False)
    op.alter_column('credentials', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Identifier of the agent this credential belongs to.',
               existing_nullable=False)
    op.alter_column('credentials', 'ephemeral_public_key',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='The ephemeral X25519 public key associated with this credential (bytes).',
               existing_nullable=False)
    op.alter_column('credentials', 'signature',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment="Signature of the ephemeral_public_key using the agent's long-term key (bytes).",
               existing_nullable=False)
    op.alter_column('credentials', 'scope',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='Scope of access granted by this credential.')
    op.alter_column('credentials', 'origin_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Optional JSON containing origin context details (hostname, IP, etc.).',
               existing_nullable=True)
    op.alter_column('credentials', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='Timestamp when the credential was issued.',
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the credential expires.',
               existing_nullable=False)
    op.alter_column('credentials', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the credential was revoked (NULL if not revoked).',
               existing_nullable=True)
    op.drop_index('ix_credentials_expires_at', table_name='credentials')
    op.drop_index('ix_credentials_revoked_at', table_name='credentials')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_credentials_revoked_at', 'credentials', ['revoked_at'], unique=False)
    op.create_index('ix_credentials_expires_at', 'credentials', ['expires_at'], unique=False)
    op.alter_column('credentials', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the credential was revoked (NULL if not revoked).',
               existing_nullable=True)
    op.alter_column('credentials', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the credential expires.',
               existing_nullable=False)
    op.alter_column('credentials', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Timestamp when the credential was issued.',
               existing_server_default=sa.text('now()'))
    op.alter_column('credentials', 'origin_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Optional JSON containing origin context details (hostname, IP, etc.).',
               existing_nullable=True)
    op.alter_column('credentials', 'scope',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='Scope of access granted by this credential.')
    op.alter_column('credentials', 'signature',
               existing_type=postgresql.BYTEA(),
               comment="Signature of the ephemeral_public_key using the agent's long-term key (bytes).",
               existing_nullable=False)
    op.alter_column('credentials', 'ephemeral_public_key',
               existing_type=postgresql.BYTEA(),
               comment='The ephemeral X25519 public key associated with this credential (bytes).',
               existing_nullable=False)
    op.alter_column('credentials', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment='Identifier of the agent this credential belongs to.',
               existing_nullable=False)
    op.alter_column('credentials', 'credential_id',
               existing_type=sa.VARCHAR(),
               comment='Unique identifier for this credential instance (e.g., cred-<uuid>)',
               existing_nullable=False)
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the agent record was created.',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'current_public_key',
               existing_type=postgresql.BYTEA(),
               comment='The current long-term Ed25519 public key for the agent (bytes).',
               existing_nullable=False)
    op.alter_column('agents', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment='Unique identifier for the agent (e.g., agent-<uuid>)',
               existing_nullable=False)
    # ### end Alembic commands ###