"""Modify secrets table for split key storage"""

# revision identifiers, used by Alembic.
revision = '556ee3ed451b'
down_revision = '5906eb3332a8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'value', new_column_name='share_1',
                    existing_type=sa.String(),
                    type_=sa.Text(),
                    comment="The first share of the split secret.")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'share_1', new_column_name='value',
                    existing_type=sa.Text(),
                    type_=sa.String(),
                    existing_comment="The first share of the split secret.",
                    comment=None)
    # ### end Alembic commands ###