"""Initial database schema for agents and credentials"""

# revision identifiers, used by Alembic.
revision = '8a916b49e686'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(), nullable=False, comment='Unique identifier for the agent (e.g., agent-<uuid>)'),
    sa.Column('current_public_key', sa.LargeBinary(), nullable=False, comment='The current long-term Ed25519 public key for the agent (bytes).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the agent record was created.'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=False)
    op.create_table('credentials',
    sa.Column('credential_id', sa.String(), nullable=False, comment='Unique identifier for this credential instance (e.g., cred-<uuid>)'),
    sa.Column('agent_id', sa.String(), nullable=False, comment='Identifier of the agent this credential belongs to.'),
    sa.Column('ephemeral_public_key', sa.LargeBinary(), nullable=False, comment='The ephemeral X25519 public key associated with this credential (bytes).'),
    sa.Column('signature', sa.LargeBinary(), nullable=False, comment="Signature of the ephemeral_public_key using the agent's long-term key (bytes)."),
    sa.Column('scope', sa.String(), nullable=False, comment='Scope of access granted by this credential.'),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the credential was issued.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the credential expires.'),
    sa.Column('origin_context', sa.JSON(), nullable=True, comment='Optional JSON containing origin context details (hostname, IP, etc.).'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the credential was revoked (NULL if not revoked).'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_index(op.f('ix_credentials_agent_id'), 'credentials', ['agent_id'], unique=False)
    op.create_index(op.f('ix_credentials_credential_id'), 'credentials', ['credential_id'], unique=False)
    op.create_index(op.f('ix_credentials_expires_at'), 'credentials', ['expires_at'], unique=False)
    op.create_index(op.f('ix_credentials_revoked_at'), 'credentials', ['revoked_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_revoked_at'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_expires_at'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_agent_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###