"""Add attestation_policies table and rename metadata column"""

# revision identifiers, used by Alembic.
revision = 'ad30f11f4f01'
down_revision = '85a042468f08'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attestation_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('KUBERNETES', 'AWS_IAM', name='platformtype'), nullable=False),
    sa.Column('selector', sa.String(), nullable=False),
    sa.Column('agent_name_to_bootstrap', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selector')
    )
    op.create_index(op.f('ix_attestation_policies_id'), 'attestation_policies', ['id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('secrets', sa.Column('secret_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('secrets', 'metadata')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Arbitrary metadata for the secret, e.g., target_base_url'))
    op.drop_column('secrets', 'secret_metadata')
    op.drop_table('policies')
    op.drop_index(op.f('ix_attestation_policies_id'), table_name='attestation_policies')
    op.drop_table('attestation_policies')
    # ### end Alembic commands ###