"""create nonces table for challenge response"""

# revision identifiers, used by Alembic.
revision = 'e91bddf1b5b4'
down_revision = '203db040fcb3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonces',
    sa.Column('nonce', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_index(op.f('ix_nonces_agent_id'), 'nonces', ['agent_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nonces_agent_id'), table_name='nonces')
    op.drop_table('nonces')
    # ### end Alembic commands ###