"""make_credentials_signature_nullable"""

# revision identifiers, used by Alembic.
revision = '13bdfc2959b8'
down_revision = 'e65664cca5ae'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'signature',
        existing_type=sa.LargeBinary(), 
        nullable=True,
        existing_nullable=False) 
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'signature',
        existing_type=sa.LargeBinary(),
        nullable=False,
        existing_nullable=True)
    # ### end Alembic commands ###