"""SQLAlchemy model for Credential entities."""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, LargeBinary, DateTime, func, ForeignKey, JSON, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID  # Keep for potential future use if switching DB

from app.db.base import Base

class Credential(Base):
    """Represents an issued credential in the database."""
    __tablename__ = "credentials"

    # Use UUID for primary key, default generated by database if possible, else python
    credential_id = Column(String, primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    agent_id = Column(String, ForeignKey("agents.agent_id"), nullable=False, index=True)

    # Store keys and signatures as binary data
    ephemeral_public_key = Column(LargeBinary, nullable=False) # X25519 key bytes
    signature = Column(LargeBinary, nullable=False) # Signature of ephemeral_public_key by agent's long-term key

    scope = Column(String, nullable=True) # Optional scope defining credential permissions
    origin_context = Column(JSON, nullable=True) # Optional JSON blob for context

    issued_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    revoked_at = Column(DateTime(timezone=True), nullable=True) # Timestamp when revoked

    # Define relationship back to Agent (optional but useful)
    agent = relationship("Agent") # Assumes Agent model is defined in models/agent.py

    # Add a computed property for easier checks (requires hybrid_property)
    # from sqlalchemy.ext.hybrid import hybrid_property
    # @hybrid_property
    # def is_active(self):
    #     return self.revoked_at is None and self.expires_at > datetime.now(timezone.utc) 