"""SQLAlchemy model for Credential entities."""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, LargeBinary, DateTime, func, ForeignKey, JSON, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID  # Keep for potential future use if switching DB

from app.db.base import Base

class Credential(Base):
    """Represents an issued credential in the database."""
    __tablename__ = "credentials"

    # Use UUID for primary key, default generated by database if possible, else python
    credential_id = Column(String, primary_key=True, index=True, default=lambda: str(uuid.uuid4()), comment="Unique identifier for this credential instance (e.g., cred-<uuid>)")
    agent_id = Column(String, ForeignKey("agents.agent_id"), nullable=False, index=True, comment="Identifier of the agent this credential belongs to.")
    # scope = Column(String, nullable=True) # TODO: Add scope to the credential
    # Store keys and signatures as binary data
    ephemeral_public_key = Column(LargeBinary, nullable=False, comment="The ephemeral X25519 public key associated with this credential (bytes).")
    signature = Column(LargeBinary, nullable=True, comment="Signature of the ephemeral_public_key using the agent's long-term key (bytes).")

    scope = Column(String, nullable=True, comment="Scope of access granted by this credential.")
    origin_context = Column(JSON, nullable=True, comment="Optional JSON containing origin context details (hostname, IP, etc.).")

    issued_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, comment="Timestamp when the credential was issued.")
    expires_at = Column(DateTime(timezone=True), nullable=False, comment="Timestamp when the credential expires.")
    revoked_at = Column(DateTime(timezone=True), nullable=True, comment="Timestamp when the credential was revoked (NULL if not revoked).")

    status = Column(String, nullable=False, default="issued", server_default="issued") # <--- ADD THIS NEW COLUMN

    # Define relationship back to Agent (optional but useful)
    agent = relationship("Agent") # Assumes Agent model is defined in models/agent.py

    # Add a computed property for easier checks (requires hybrid_property)
    # from sqlalchemy.ext.hybrid import hybrid_property
    # @hybrid_property
    # def is_active(self):
    #     return self.revoked_at is None and self.expires_at > datetime.now(timezone.utc) 